### ISSUE TITLE
Octoprint 1.4 timeout on plug-in with stock melzi on ender 3 pro

### ISSUE THREAD

**Issue by perfessor101** [LuckyX182/Filament_sensor_simplified#12]
Hello, waited for a filament change, right at printer and the alarm goes off and I’m ready. 
Next reel already on printer. Buzzer goes nozzle moves away from print. rush to exchange filament. New filament fed in to nozzle. Hit knob on printer and it moves back to printing position after serial communications have timed out  ...

Only way I could have been faster is if the extruder retracted about 350 mm before change and then fed in 350 mm filament after. 

I’ll see what I can change in printer timeouts on the stock install

**Comment by LuckyX182** [comment]
I didn't have such issues with serial connection, I dont't think this has something to do with this plugin.
