### ISSUE TITLE
Pause for user is triggered twice when changing filament

### ISSUE THREAD

**Issue by sgruby** [LuckyX182/Filament_sensor_simplified#20]
I have Gcode added in Cura to change filament at a certain layer. This adds an M600 command to change the filament. When the filament is unloaded, it triggers this plugin which then sends another M600 command to change the filament. Instead of modifying the Cura Gcode (standard plugin to add the filament change), this plugin should see that the M600 is called and not call it again.

**Comment by LazeMSS** [comment]
Duplicate of #18 ?

**Comment by sgruby** [comment]
Yes, it does appear to be a duplicate of that. I'll go ahead and close it out. I must have overlooked the issue when I posted.
