### ISSUE TITLE
Sometimes print is not paused

### ISSUE THREAD

**Issue by bartoszwas** [LuckyX182/Filament_sensor_simplified#25]
h

**Comment by Fredlepp** [comment]
i'm testing from an hour, and the plug-in don't stop printing. a pop up appear to advertise me  "filament run out", but the print continues.

the printer don't see the M600 command?

tried on a creality ender 3 with marlin 2.0.7

**Comment by bartoszwas** [comment]
I think I know what the problem is. Plugin works but print is not paused directly after filament runout. Octorpint tries to finish sent commands or is still sending commands I'm not sure.

I have changed plugin to "Filament Sensor Reloaded" and it works fine...

**Comment by Fredlepp** [comment]
i didn't modify the configuration file, but i wil try to send a M600 in the terminal to look if it make something

**Comment by endurance1968** [comment]
Then the issue is closed?

**Comment by Fredlepp** [comment]
yes

**Comment by LazeMSS** [comment]
@Fredlepp  please the issue then :)

**Comment by Fredlepp** [comment]
it's not me who has create this issue, sorry
