### ISSUE TITLE
Featurerequest: Small status icon on titlebar would be great

### ISSUE THREAD

**Issue by endurance1968** [LuckyX182/Filament_sensor_simplified#28]
Hello,

It would be great o have a small icon showing the filament status on the title (similar as in filament reloaded).
With setting disabled/enabled for people who don't want this extra icon.

E.g. 

- green circle if Fila is correctly loaded
- red circle if fila is missing
- grey if disabled

thx in advance

**Comment by endurance1968** [comment]
E.g. green 

- circle if Fila is correctly loaded
- red circle if fila is missing
- grey if disabled

**Comment by LuckyX182** [comment]
This is not a bad idea

**Comment by LuckyX182** [comment]
Added.
