### ISSUE TITLE
Multiple gcodes?

### ISSUE THREAD

**Issue by slvrsky07** [LuckyX182/Filament_sensor_simplified#31]
Is there a way to add more than one gcode to be triggered? I would like it to do M25 and also an action item like M118 if possible.

**Comment by concres** [comment]
I don't know if you already found a way, but one option that I tested in other similar plugins and worked was to edit the scripts `After print job is paused` and `Before print job is resumed` on the OctoPrint. [This](https://docs.octoprint.org/en/master/features/gcode_scripts.html#more-nifty-pause-and-resume) page show a great example. In this plugin I don't test it yet.

**Comment by LuckyX182** [comment]
No, currently there is only one gcode command possible.
