### ISSUE TITLE
Resume without filament cancels print

### ISSUE THREAD

**Issue by JonSnow88** [LuckyX182/Filament_sensor_simplified#42]
So when the sensor detects no filament during a print it pauses, if you select "Resume" from octoprint and still have no filament loaded it just straight up cancels the print without warning.

I understand most people would only select "Resume" after loading filament but it shouldn't just cancel the print without warning, its a good thing I tested this as its a simple mistake that could ruin a print.

The reloaded plugin works as expected, resume does nothing when there is no filament.

**Comment by LuckyX182** [comment]
Fixed in 0.3.0
