### ISSUE TITLE
Plugin Interferes with mid print filament change

### ISSUE THREAD

**Issue by LewisSpring** [LuckyX182/Filament_sensor_simplified#43]
Hello,
Would it be possible to have the script automatically temporarily disable itself during a M600 in Gcode for multi-colour prints?
I've found that as I'm removing the filament from the printer during the GCode-triggered M600, It seems to activate another M600.
It didn't seem to cause the filament to retract like the first time M600 was ran, but everything else seemed to have happened multiple times.

![image](https://user-images.githubusercontent.com/40576482/147360798-dd1ec39f-b737-40d9-91d3-60ffb166418a.png)
These happened during the print, I think.

Thank you.

**Comment by LuckyX182** [comment]
Hello, please try with the latest version.

Luke

**Comment by LewisSpring** [comment]
Hi there Luke,
I haven't printed for a while, but I'll get back to you as soon as possible.

**Comment by LewisSpring** [comment]
Hi Luke, 
I did a print with the new version:
Seems to work great! No interference as far as I can tell.

Cheers!

**Comment by LuckyX182** [comment]
Superb!
