### ISSUE TITLE
pin selection

### ISSUE THREAD

**Issue by DCullen2020** [LuckyX182/Filament_sensor_simplified#46]
Sorry for the newbe question here. I have a raspberry 3b plus and using pin 1 for the 3v3 power, pin 9 for the ground and tried pins 13,15 for the last wire. I am unable to get this to work.

![image](https://user-images.githubusercontent.com/75028109/150917495-cadf273a-b32a-4be3-8010-86f863f4dbb0.png)

I constantly get sensor triggered but no filament detected. Ender 5 plus, running latest Octoprint, using this plugin. 

![image](https://user-images.githubusercontent.com/75028109/150917682-214ea14e-684e-4995-b924-08e2cf669bbc.png)

**Comment by Rushmonk** [comment]
Hello, 
as you have picked GPIO you need to choose the correct number for it. Pin 13 (physical) = GPIO No. 27 and Pin 15 (physical) = GPIO No. 22! If you got a 3 pin connector make sure using the right pins: VSG or VGS (V: Volt=3,3V Pin) (S: Signal=GPIO Pin that you choose) (G: Ground, is obviously). Also depending on your sensor, if it's NO=Normaly Open or NC=Normaly Closed, this is basically the unused status, if unsure try both switch types in the dropdown menu and test.

Hope this helps.
