### ISSUE TITLE
Unable to use plugin

### ISSUE THREAD

**Issue by chickenrun81** [LuckyX182/Filament_sensor_simplified#60]
Hello.
Yesterday,i would like to use your plugin, but this error appear, and i don't know how to solve it. Can you help me please?
![octoprint](https://user-images.githubusercontent.com/114053880/191432119-cf856dd8-e6d7-4ac7-aba9-c5e6b11e0de0.jpg)

**Comment by loroff** [comment]
apparement un autre plug in interfaire avec celui la moi il s agissait du plug in Exclude Region

**Comment by chickenrun81** [comment]
Bonjour. Le plugin fonctionne à nouveau, sans rien avoir fait.
