### ISSUE TITLE
Feature Request" Ability to change g-code sent to pause.

### ISSUE THREAD

**Issue by a-woolf** [LuckyX182/Filament_sensor_simplified#7]
I have a Monoprice Maker Select v2.  The plugin shows dozens of notifications that the filament is out, but doesn't pause the print.
("M600" doesn't pause the Maker Select v2. "M25" needs to be sent instead. )
Can you add an option to change the g-code used for pausing?

**Comment by LuckyX182** [comment]
Option added in new version.
