### ISSUE TITLE
BCM pin numbering vs Board pin numbering, and interaction with other plugins

### ISSUE THREAD

**Issue by git-jonathankinney** [LuckyX182/Filament_sensor_simplified#8]
So a weird thing that may not specifically be a bug with your plugin, but still an issue.  I used another plugin called "PSU Control" which I used BCM pin numbering, and until I switched to Board pin numbering, I could not get "Filament Sensor Simplified" to work.  The moment I changed all plugins to use Board pin numbering, **BOOM**, this "Filament Sensor Simplified" started working 100% as expected.  You may want to put a warning message like the others, on the plugin settings page.  I don't know why there is cross plugin interference, but it seems to be there.  Digging through bug reports around these plugins, there were hints pointing in this direction, but I have not seen anyone directly call it out.  It is a thing, and it is worth mentioning.  Without more information on the root cause of this cross plugin interaction, all I can suggest/request is a note/warning on the plugin settings page.

**Comment by LuckyX182** [comment]
Issue fixed in new version.
